context:
  name: beckhoff-ads
  tag: 113.0.32-1
  version: "113.0.34-1"

recipe:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/Beckhoff/ADS/archive/refs/tags/${{ tag }}.tar.gz
  sha256: c48110f4f1bd910809c90f2f4275eee658a26cbbbc544a981a1ebd53facebfd5
  patches:
    # Patch to build shared libs and install executables
    - meson-build.patch

build:
  number: 0
  skip:
    - win
  script: |
    meson setup build --prefix="$PREFIX" -Dlibdir="$PREFIX/lib" -Dwerror=false
    ninja -C build install

outputs:
  - package:
      name: ${{ name }}
    requirements:
      build:
        - ${{ stdlib("c") }}
        - ${{ compiler('cxx') }}
        - meson
        - ninja
      run_exports:
        - ${{ pin_subpackage(name, upper_bound='x.x.x') }}
    build:
      files:
        - include
        - bin
        - if: linux
          then:
            - lib/*.so*
        - if: osx
          then:
            - lib/*.dylib*
        - lib/pkgconfig
    tests:
      - script:
          - test -d "${PREFIX}/include/AdsLib"
          - test -d "${PREFIX}/include/AdsLib/bhf"
          - test -d "${PREFIX}/include/AdsLib/standalone"
          - test -d "${PREFIX}/include/AdsLib/TwinCAT"
          - test -f "${PREFIX}/include/AdsLib/AdsDef.h"
          - test -f "${PREFIX}/include/AdsLib/AdsNotification.h"
          - test -f "${PREFIX}/include/AdsLib/AmsPort.h"
          - test -f "${PREFIX}/include/AdsLib/NotificationDispatcher.h"
          - test -f "${PREFIX}/include/AdsLib/RouterAccess.h"
          - test -f "${PREFIX}/include/AdsLib/AdsDevice.h"
          - test -f "${PREFIX}/include/AdsLib/AdsNotificationOOI.h"
          - test -f "${PREFIX}/include/AdsLib/AmsRouter.h"
          - test -f "${PREFIX}/include/AdsLib/RTimeAccess.h"
          - test -f "${PREFIX}/include/AdsLib/Semaphore.h"
          - test -f "${PREFIX}/include/AdsLib/AdsException.h"
          - test -f "${PREFIX}/include/AdsLib/AdsVariable.h"
          - test -f "${PREFIX}/include/AdsLib/Frame.h"
          - test -f "${PREFIX}/include/AdsLib/RegistryAccess.h"
          - test -f "${PREFIX}/include/AdsLib/Sockets.h"
          - test -f "${PREFIX}/include/AdsLib/wrap_endian.h"
          - test -f "${PREFIX}/include/AdsLib/AdsFile.h"
          - test -f "${PREFIX}/include/AdsLib/AmsConnection.h"
          - test -f "${PREFIX}/include/AdsLib/LicenseAccess.h"
          - test -f "${PREFIX}/include/AdsLib/RingBuffer.h"
          - test -f "${PREFIX}/include/AdsLib/SymbolAccess.h"
          - test -f "${PREFIX}/include/AdsLib/wrap_registry.h"
          - test -f "${PREFIX}/include/AdsLib/AdsLib.h"
          - test -f "${PREFIX}/include/AdsLib/AmsHeader.h"
          - test -f "${PREFIX}/include/AdsLib/Log.h"
          - test -f "${PREFIX}/include/AdsLib/Router.h"
          - test -f "${PREFIX}/include/AdsLib/wrap_socket.h"
          - test -f "${PREFIX}/include/AdsLib/bhf/ParameterList.h"
          - test -f "${PREFIX}/include/AdsLib/bhf/StringToInteger.h"
          - test -f "${PREFIX}/include/AdsLib/bhf/WindowsQuirks.h"
          - test -f "${PREFIX}/include/AdsLib/standalone/AdsDef.h"
          - test -f "${PREFIX}/include/AdsLib/standalone/AdsLib.h"
          - test -f "${PREFIX}/include/AdsLib/TwinCAT/AdsDef.h"
          - test -f "${PREFIX}/include/AdsLib/TwinCAT/AdsLib.h"
          - if: linux
            then:
              - test -f "${PREFIX}/lib/libAdsLib.so"
          - if: osx
            then:
              - test -f "${PREFIX}/lib/libAdsLib.dylib"
          - adstool --help

  - package:
      name: ${{ name }}-static
    requirements:
      build:
        - ${{ stdlib("c") }}
        - ${{ compiler('cxx') }}
        - meson
        - ninja
    build:
      files:
        - lib/*.a
    tests:
      - script:
          - test -f "${PREFIX}/lib/libAdsLib.a"

about:
  homepage: https://github.com/Beckhoff/ADS
  license: MIT
  license_file: LICENSE
  summary: Beckhoff protocol to communicate with TwinCAT devices
  description: |
    This library is intended to provide easy use as ADS client applications running on non-windows systems 
    (e.g. FreeBSD, Linux, ...) to communicate with TwinCAT devices via TCP/IP.
  documentation: https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_ads_intro/index.html
  repository: https://github.com/Beckhoff/ADS

extra:
  recipe-maintainers:
    - AndreFavotto
    - mac-kan
    - javicereijo
